// Generated by CoffeeScript 1.10.0
var Pre;

module.exports = Pre = (function() {
  function Pre() {}

  Pre.attribute = 'pre';

  Pre.priority = 1001;

  Pre.terminal = true;

  return Pre;

})();

//# sourceMappingURL=pre.js.map
