// Generated by CoffeeScript 1.10.0
var Mutation;

module.exports = Mutation = (function() {
  function Mutation(node) {
    this.node = node;
    return;
  }

  Mutation.prototype.reset = function() {};

  return Mutation;

})();

//# sourceMappingURL=mutation.js.map
