// Generated by CoffeeScript 1.10.0
var ref, ref1, ref2, ref3, ref4;

module.exports = ((ref = window.requestAnimationFrame) != null ? ref.bind(window) : void 0) || ((ref1 = window.webkitRequestAnimationFrame) != null ? ref1.bind(window) : void 0) || ((ref2 = window.mozRequestAnimationFrame) != null ? ref2.bind(window) : void 0) || ((ref3 = window.oRequestAnimationFrame) != null ? ref3.bind(window) : void 0) || ((ref4 = window.msRequestAnimationFrame) != null ? ref4.bind(window) : void 0) || function(callback, element) {
  return window.setTimeout(callback, 1000 / 60);
};

//# sourceMappingURL=animation-frame.js.map
