// Generated by CoffeeScript 1.10.0
var Map;

module.exports = window['Map'] || (Map = (function() {
  function Map() {
    this.keys = [];
    this.values = [];
    return;
  }

  Map.prototype.get = function(key) {
    var index;
    index = this.keys.indexOf(key);
    return this.values[index];
  };

  Map.prototype.set = function(key, value) {
    var index;
    index = this.keys.indexOf(key);
    if (index !== -1) {
      this.values[index] = value;
    } else {
      this.keys.push(key);
      this.values.push(value);
    }
    return value;
  };

  Map.prototype.has = function(key) {
    var index;
    index = this.keys.indexOf(key);
    return index !== -1;
  };

  Map.prototype["delete"] = function(key) {
    var index;
    index = this.keys.indexOf(key);
    if (index !== -1) {
      this.keys.splice(index, 1);
      this.values.splice(index, 1);
    }
  };

  return Map;

})());

//# sourceMappingURL=map.js.map
