// Generated by CoffeeScript 1.10.0
var Selection;

module.exports = Selection = (function() {
  function Selection() {
    this.selection = getSelection();
    this.activeElement = null;
    this.selectable = false;
    this.selectionStart = 0;
    this.selectionEnd = 0;
    this.ranges = [];
    return;
  }

  Selection.prototype.clear = function() {
    this.anchorNode = null;
    this.anchorOffset = null;
    this.focusNode = null;
    this.focusOffset = null;
  };

  Selection.prototype.save = function() {
    var index, range;
    this.activeElement = document.activeElement;
    this.selectable = this.isSelectable(this.activeElement);
    if (this.selectable) {
      this.selectionStart = this.activeElement.selectionStart;
      this.selectionEnd = this.activeElement.selectionEnd;
    } else {
      this.ranges = (function() {
        var i, ref, results;
        results = [];
        for (index = i = 0, ref = this.selection.rangeCount; 0 <= ref ? i < ref : i > ref; index = 0 <= ref ? ++i : --i) {
          range = this.selection.getRangeAt(index);
          results.push({
            startContainer: range.startContainer,
            startOffset: range.startOffset,
            endContainer: range.endContainer,
            endOffset: range.endOffset
          });
        }
        return results;
      }).call(this);
    }
  };

  Selection.prototype.restore = function() {
    if (this.selectable) {
      if (this.activeElement !== document.activeElement) {
        this.activeElement.focus();
      }
      this.activeElement.selectionStart = this.selectionStart;
      this.activeElement.selectionEnd = this.selectionEnd;
    } else {
      return;
    }
  };

  Selection.prototype.isSelectable = function(node) {
    if (!node) {
      return false;
    }
    if (node.tagName === 'INPUT') {
      return /^(text|search|password|tel|url)$/.test(node.type);
    }
    if (node.tagName === 'TEXTAREA') {
      return true;
    }
    return false;
  };

  return Selection;

})();

//# sourceMappingURL=selection.js.map
