// Generated by CoffeeScript 1.10.0
var Comment, DOM, Element, HtmlParser, Img, Input, Text;

Element = require('./nodes/element');

Comment = require('./nodes/comment');

Text = require('./nodes/text');

HtmlParser = require('./core/html-parser');

Input = require('./nodes/input');

Img = require('./nodes/img');

module.exports = DOM = (function() {
  function DOM() {}

  DOM.elements = {
    input: Input,
    img: Img
  };

  DOM.createElement = function(type, attrs) {
    var Constructor;
    Constructor = this.elements[type] || Element;
    return new Constructor(type, attrs);
  };

  DOM.createText = function(text) {
    return new Text(text);
  };

  DOM.createComment = function(text) {
    return new Comment(text);
  };

  DOM.registerElement = function(type, Constructor) {
    this.elements[type] = Constructor;
  };

  DOM.parse = function(html) {
    if (this.htmlParser == null) {
      this.htmlParser = new HtmlParser();
    }
    return this.htmlParser.parse(html);
  };

  DOM.on = function(event, handler) {
    window.addEventListener(event, handler);
  };

  DOM.off = function(event, handler) {
    window.removeEventListener(event, handler);
  };

  DOM.one = function(event, handler) {
    var dom, wrapper;
    dom = this;
    wrapper = function() {
      var returns;
      returns = handler.apply(this, arguments);
      dom.off(event, wrapper);
      return returns;
    };
    this.on(event, wrapper);
  };

  return DOM;

})();

//# sourceMappingURL=index.js.map
