// Generated by CoffeeScript 1.10.0
var Directive,
  hasProp = {}.hasOwnProperty;

module.exports = Directive = (function() {
  function Directive() {}

  Directive.priority = 0;

  Directive.attribute = '';

  Directive.terminal = false;

  Directive.create = function(Class) {
    var key, value;
    for (key in this) {
      if (!hasProp.call(this, key)) continue;
      value = this[key];
      if (typeof value !== 'function') {
        Class[key] = Class[key] || value;
      }
    }
    return Class;
  };

  return Directive;

})();

//# sourceMappingURL=directive.js.map
