// Generated by CoffeeScript 1.10.0
var Directive,
  hasProp = {}.hasOwnProperty;

module.exports = Directive = (function() {
  function Directive() {}

  Directive.priority = 0;

  Directive.attribute = '';

  Directive.terminal = false;

  Directive.compileDirectives = function(components) {
    return components.map(function(DirClass) {
      return Directive.create(DirClass);
    });
  };

  Directive.create = function(DirClass) {
    var key, value;
    for (key in this) {
      if (!hasProp.call(this, key)) continue;
      value = this[key];
      if (typeof value !== 'function') {
        DirClass[key] = DirClass[key] || value;
      }
    }
    return DirClass;
  };

  return Directive;

})();

//# sourceMappingURL=directive.js.map
