// Generated by CoffeeScript 1.10.0
var Platform;

module.exports = Platform = (function() {
  function Platform() {
    var userAgent;
    userAgent = navigator.userAgent;
    this.edge = /Edge/.test(userAgent);
    this.chrome = /Chrome/.test(userAgent) && !this.edge;
    this.firefox = /Firefox/.test(userAgent);
    this.ie = /Trident/.test(userAgent);
    this.ms = this.ie || this.edge;
    return;
  }

  return Platform;

})();

//# sourceMappingURL=platform.js.map
