// Generated by CoffeeScript 1.10.0
var ShadowStyle;

module.exports = ShadowStyle = (function() {
  var cssBlockRegExp, partsRegExp;

  function ShadowStyle() {}

  cssBlockRegExp = /([\s\S]+?)\s*(\{[\s\S]*?})/img;

  partsRegExp = /([^,]+)/img;

  ShadowStyle.compile = function(style) {
    if (typeof style === 'function') {
      return style;
    }
    style = style.toString();
    return this.createStyleGenerator(style);
  };

  ShadowStyle.replace = function(selector, id, components) {
    var childParts, lastChildPart;
    if (components == null) {
      components = [];
    }
    childParts = selector.split(/\s+|>/);
    lastChildPart = childParts[childParts.length - 1];
    if (!/:host/.test(lastChildPart)) {
      lastChildPart = lastChildPart.replace(/^(.+?)(:.+)?$/, "$1[c" + id + "]$2");
      childParts[childParts.length - 1] = lastChildPart;
      selector = childParts.join(' ');
    }
    selector = selector.replace(/:host/img, "[h" + id + "]");
    return selector;
  };

  ShadowStyle.createStyleGenerator = function(style) {
    var generatorArgs, generatorBody;
    style = style.replace(/\s*(\r|\n|\r\n)\s*/img, '');
    style = style.replace(/"/img, '\\"');
    style = style.replace(cssBlockRegExp, function(match, selector, rules) {
      selector = selector.replace(partsRegExp, '" + replace("$1", id, components) + "');
      return selector + rules;
    });
    generatorArgs = 'id, components';
    generatorBody = "var replace = " + this.replace + "; return \"" + style + "\"";
    return new Function(generatorArgs, generatorBody);
  };

  return ShadowStyle;

})();

//# sourceMappingURL=shadow-style.js.map
