// Generated by CoffeeScript 1.10.0
var ShadowStyle;

module.exports = ShadowStyle = (function() {
  var cssBlockRegExp, partsRegExp;

  function ShadowStyle() {}

  cssBlockRegExp = /([\s\S]+?)\s*(\{[\s\S]*?})/img;

  partsRegExp = /([^,]+)/img;

  ShadowStyle.compile = function(style) {
    if (typeof style === 'function') {
      return style;
    }
    return this.createStyleGenerator(style.toString());
  };

  ShadowStyle.replace = function(selector, id, components) {
    var componentTags, parts;
    if (components == null) {
      components = [];
    }
    componentTags = components.map((function(_this) {
      return function(component) {
        return component.selector;
      };
    })(this));
    parts = selector.split(/\s+|>/).map((function(_this) {
      return function(part, index, parts) {
        if (index === parts.length - 1 && !/:host/.test(part)) {
          part = part.replace(/^(.+?)(:.+)?$/, "$1[c" + id + "]$2");
        }
        part = part.replace(/:host/img, "[h" + id + "]");
        part = part.replace(/^[\w\-]+/, function(tag) {
          if (componentTags.indexOf(tag) !== -1) {
            return "ui-" + tag;
          }
          return tag;
        });
        return part;
      };
    })(this));
    return parts.join(' ');
  };

  ShadowStyle.createStyleGenerator = function(style) {
    var generatorArgs, generatorBody;
    style = style.replace(/\s*(\r|\n|\r\n)\s*/img, '');
    style = style.replace(/"/img, '\\"');
    style = style.replace(cssBlockRegExp, function(match, selector, rules) {
      selector = selector.replace(partsRegExp, '" + replace("$1", id, components) + "');
      return selector + rules;
    });
    generatorArgs = 'id, components';
    generatorBody = "var replace = " + this.replace + "; return \"" + style + "\"";
    return new Function(generatorArgs, generatorBody);
  };

  return ShadowStyle;

})();

//# sourceMappingURL=shadow-style.js.map
