// Generated by CoffeeScript 1.10.0
var Utils;

module.exports = Utils = (function() {
  function Utils() {}

  Utils.toArray = function(item) {
    if (item instanceof Array) {
      return item;
    }
    return [item];
  };

  return Utils;

})();

//# sourceMappingURL=utils.js.map
